# Offenses still to be fixed:
inherit_from: .rubocop_todo.yml

# Do not check code borrowed from ActiveSupport
AllCops:
  Exclude:
    - 'lib/dbus/core_ext/**/*.rb'

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#arrays
Style/WordArray:
  Enabled: false

Style/IndentationConsistency:
  Exclude:
    # a conflict between markdown and ruby indentation
    - examples/doc/variants.rb

# I am not ready to fix these
Style/IfUnlessModifier:
  Enabled: false

# I am not ready to fix these
Style/WhileUntilModifier:
  Enabled: false

# I am not ready to fix these
Style/NegatedIf:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: "nil"

# Prefer readability over performance
Performance/RedundantBlockCall:
  Enabled: false

# Need to check whether API stays OK
Lint/InheritException:
  Exclude:
    - 'lib/dbus.rb'
    - 'lib/dbus/auth.rb'
    - 'lib/dbus/bus.rb'
    - 'lib/dbus/introspect.rb'
    - 'lib/dbus/marshall.rb'
    - 'lib/dbus/matchrule.rb'
    - 'lib/dbus/message.rb'
    - 'lib/dbus/type.rb'

# Offense count: 7
Lint/HandleExceptions:
  Exclude:
    - 'lib/dbus/marshall.rb'
    - 'lib/dbus/message_queue.rb'
    - 'lib/dbus/xml.rb'
    - 'spec/server_spec.rb'
    - 'spec/service_newapi.rb'

# Offense count: 5
Lint/RescueException:
  Exclude:
    - 'examples/gdbus/gdbus'
    - 'examples/no-introspect/nm-test.rb'
    - 'lib/dbus/bus.rb'
    - 'lib/dbus/message_queue.rb'


# disable foo, _ = -> foo, = b/
# WTF: spec/introspect_xml_parser_spec.rb
#-    interfaces, _ = DBus::IntrospectXMLParser.new(xml).parse
#+    interfaces, = DBus::IntrospectXMLParser.new(xml).parse
