# Offenses still to be fixed:
inherit_from: .rubocop_todo.yml

# Do not check code borrowed from ActiveSupport
AllCops:
  Exclude:
    - 'lib/dbus/core_ext/**/*.rb'

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#arrays
Style/WordArray:
  Enabled: false

Style/IndentationConsistency:
  Exclude:
    # a conflict between markdown and ruby indentation
    - examples/doc/variants.rb
