language: ruby
rvm:
  - "2.0.0"
  - "1.9.3"
  - "1.8.7"
  - jruby-19mode
  - jruby-18mode
  - rbx-19mode
  - rbx-18mode
  - ruby-head
gemfile: Gemfile.ci
matrix:
  allow_failures:
    - rvm: ruby-head
