language: ruby
rvm:
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode
  - ruby-head
  - rbx
gemfile: Gemfile.ci
matrix:
  allow_failures:
    - rvm: "1.9.3"
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: rbx
env:
  - TESTOPTS=-v
